--liquibase formatted sql

--changeset icekubit:1
CREATE TABLE IF NOT EXISTS users
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL,
    name     VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

--changeset icekubit:2
CREATE TABLE IF NOT EXISTS tasks
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    header       VARCHAR(255) NOT NULL,
    text         VARCHAR NOT NULL,
    owner        INT,
    status       VARCHAR(255) NOT NULL,
    completed_at TIMESTAMP,

    FOREIGN KEY (owner) REFERENCES users(id)
);